twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes:
    - bootstrap_4_layout.html.twig
  globals:
    categoryRepository: "@App\\Repository\\CategoryRepository"
    cartService: "@App\\Cart\\CartService"
# De cette façon, je rend mon categoryRepository ainsi que mon cartService accessible à TOUT mes templates, grâce à la création de la variable globale.