twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes:
    - bootstrap_4_layout.html.twig
  globals:
    categoryRepository: "@App\\Repository\\CategoryRepository"
# De cette façon, je rend mon categoryRepository accessible à TOUT mes templates, grâce à la création de la variable globale