#App\Entity\Product:
#  properties:
#    name:
#      - NotBlank: { message: "Le nom du produit doit être renseigné" }
#      - Length: { min: 3, max: 255, minMessage: "Le nom du produit doit comporter au moins 3 caractères." }
#    price:
#      - NotBlank: { message: "Le prix du produit doit être renseigné." }
#
#m